// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1QbjKOAVjNPlTvdfD3nS0IYKfska_IY',
    appId: '1:601197016028:web:8aca17142a2fc287ea1519',
    messagingSenderId: '601197016028',
    projectId: 'rooh-2097e',
    authDomain: 'rooh-2097e.firebaseapp.com',
    storageBucket: 'rooh-2097e.firebasestorage.app',
    measurementId: 'G-Z13KBHKEB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMoiMXPlZWnySxqdrqh-ldLZlfO8iXanI',
    appId: '1:601197016028:android:152f9d1c085f644cea1519',
    messagingSenderId: '601197016028',
    projectId: 'rooh-2097e',
    storageBucket: 'rooh-2097e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEGpPgxravg932hLoMjh9AiTxt74BX5qo',
    appId: '1:601197016028:ios:fc90ba88bc5617a0ea1519',
    messagingSenderId: '601197016028',
    projectId: 'rooh-2097e',
    storageBucket: 'rooh-2097e.firebasestorage.app',
    iosBundleId: 'com.example.rooh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEGpPgxravg932hLoMjh9AiTxt74BX5qo',
    appId: '1:601197016028:ios:fc90ba88bc5617a0ea1519',
    messagingSenderId: '601197016028',
    projectId: 'rooh-2097e',
    storageBucket: 'rooh-2097e.firebasestorage.app',
    iosBundleId: 'com.example.rooh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr1QbjKOAVjNPlTvdfD3nS0IYKfska_IY',
    appId: '1:601197016028:web:9810dc017001d1abea1519',
    messagingSenderId: '601197016028',
    projectId: 'rooh-2097e',
    authDomain: 'rooh-2097e.firebaseapp.com',
    storageBucket: 'rooh-2097e.firebasestorage.app',
    measurementId: 'G-T7XLJ2XMLF',
  );
}
